### PR TITLE
Rectangular connections to WEIS

### PR DESCRIPTION
**Pull request by dzalkind**
## Purpose
Cherry-picking @yqliaohk 's openmdao updates in #51 and pointing to master, so we can use these connections in WEIS.

I removed the VolturnUS rect test case and merged it into a single test case generated by the WEIS example: https://github.com/WISDEM/WEIS/blob/develop/examples/15_RAFT_Studies/weis_driver_raft_opt.py

## Type of change
What types of change is it?
_Select the appropriate type(s) that describe this PR_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (non-backwards-compatible fix or feature)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Documentation update
- [ ] Maintenance update
- [ ] Other (please describe)

## Testing
Explain the steps needed to test the new code to verify that it does indeed address the issue and produce the expected behavior.

## Checklist
_Put an `x` in the boxes that apply._

- [ ] I have run existing tests which pass locally with my changes
- [ ] I have added new tests or examples that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation

### CODE REVIEW

**Comment by dzalkind** [comment]
@yqliaohk, @lucas-carmo, does this require anything in `dev` or can it be merged into `master`?

**Comment by lucas-carmo** [comment]
@dzalkind I took a look at the changed files and couldn't identify anything that would require `dev`. What do you think, @yqliaohk?

**Comment by yqliaohk** [comment]
> @dzalkind I took a look at the changed files and couldn't identify anything that would require `dev`. What do you think, @yqliaohk?

@dzalkind @lucas-carmo @gbarter 
Sorry for the late response! There are some bug fixes on the rectangular member related calculations that are only in dev branch right now (https://github.com/WISDEM/RAFT/commits/dev/?before=9b0509974150342cbef2e7d4a3eecc326ed84a32+105)  , but it should be able to run with master to create rectangular members.

**Comment by lucas-carmo** [comment]
You're right, I forgot about that bug fix! 
As far as I remember, it fixes the hydrostatics of surface piercing rectangular elements. But it's not a huge change, I would say it's only relevant for a rectangular spar. For semisubs with rectangular columns, hydrostatics would be very slightly off (depending on the distance between columns). For semisubs with rectangular pontoons, that bug fix has no impact whatsoever.

I think this PR is safe to be merged.

**Comment by mattEhall** [comment]
I agree, good to merge

**Pull request merged**
